name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: ./data-scripts
        env:
          prev: ${{ github.event.base_ref }}
        run: |
          git fetch
          echo $(prev)
          echo $(git diff --name-only $(prev))
          node automagically-updating-version-json.js $(git diff origin/master HEAD --name-only)
          sh the-script.sh
      - working-directory: ./
        run: |
          git add .
          git commit -m "automagically updated version.js and generated json files"
          git push origin master