name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - working-directory: ./data-scripts
        env:
          PREV: ${{ github.event.before }}
        run: |
          git fetch
          echo "$PREV"
          echo $(git diff --name-only "$PREV")
          node ./create-search-psalter-data.js
          node automagically-updating-version-json.js $(git diff "$PREV" --name-only)
          node ./data-minifier.js
      - working-directory: ./
        run: |
          git add .
          git status
          git commit -m "automagically updated version.js and generated json files"
          git push origin master